### ISSUE TITLE
ActionController::InvalidAuthenticityToken at /pagelets/comments

### ISSUE THREAD

**Issue by rubyconvict** [antulik/pagelet_rails_demo_app#1]
```
ActionController::InvalidAuthenticityToken at /pagelets/comments
================================================================

> ActionController::InvalidAuthenticityToken

actionpack (5.0.0.1) lib/action_controller/metal/request_forgery_protection.rb, line 195
----------------------------------------------------------------------------------------

``` ruby
  190           def initialize(controller)
  191             @controller = controller
  192           end
  193   
  194           def handle_unverified_request
![screen](https://cloud.githubusercontent.com/assets/34706/24035045/1bdb15d4-0af4-11e7-949c-96b9f96888cd.jpg)

> 195             raise ActionController::InvalidAuthenticityToken
  196           end
  197         end
  198       end
  199   
  200       protected
```

App backtrace
-------------

Full backtrace
--------------

 - actionpack (5.0.0.1) lib/action_controller/metal/request_forgery_protection.rb:195:in `handle_unverified_request'
 - actionpack (5.0.0.1) lib/action_controller/metal/request_forgery_protection.rb:223:in `handle_unverified_request'
 - actionpack (5.0.0.1) lib/action_controller/metal/request_forgery_protection.rb:218:in `verify_authenticity_token'
 - activesupport (5.0.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
 - activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
 - actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
 - activesupport (5.0.0.1) lib/active_support/callbacks.rb:170:in `block in halting'
 - activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `block in call'
 - activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `call'
 - activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
 - activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
 - activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
 - actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
 - actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
 - actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
 - activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
 - activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
 - activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'
 - actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
 - actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
 - activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
 -  () home/me/.rvm/gems/ruby-2.3.1/bundler/gems/pagelet_rails-a3753c224768/lib/pagelet_rails/concerns/response_wrapper.rb:5:in `process_action'
 - actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'
 - actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'
 - actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'
 - actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'
 - actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 - actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
 - actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
 - actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
 - actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
 - rack (2.0.1) lib/rack/etag.rb:25:in `call'
 - rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
 - rack (2.0.1) lib/rack/head.rb:12:in `call'
 - rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
 - rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
 - actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
 - activerecord (5.0.0.1) lib/active_record/migration.rb:552:in `call'
 - actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
 - activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
 - activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
 - activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
 - actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
 - actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
 - actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
 - actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
 - actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
 - railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
 - railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
 - activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
 - activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
 - activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
 - railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
 - sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
 - actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
 - rack (2.0.1) lib/rack/method_override.rb:22:in `call'
 - rack (2.0.1) lib/rack/runtime.rb:22:in `call'
 - activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
 - actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
 - actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
 - rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
 - railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
 - puma (3.5.2) lib/puma/configuration.rb:225:in `call'
 - puma (3.5.2) lib/puma/server.rb:569:in `handle_request'
 - puma (3.5.2) lib/puma/server.rb:406:in `process_client'
 - puma (3.5.2) lib/puma/server.rb:271:in `block in run'
 - puma (3.5.2) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by rubyconvict** [comment]
![screen](https://cloud.githubusercontent.com/assets/34706/24035065/38aaa6de-0af4-11e7-8380-ef9d05a4dd55.jpg)

**Comment by antulik** [comment]
Thanks for the report. 

The issue was: the demo app globaly uses streaming mode, however rails does not support cookies well in streaming mode. So what's end up happening the cookies are not sent to the browser. The temporary solution for this app was to disable CSRF because of streaming on all pages. 

The demo app should be working correctly now.

However there are other work arounds, one of:

- make sure cookies are set before navigating to the page in streaming mode
- don't use streaming if writing to session is important
- wait until pagelet gem adds proper support for cookies in rails streaming
