### ISSUE TITLE
Total comments counters do not refresh after deleting a comment

### ISSUE THREAD

**Issue by rubyconvict** [antulik/pagelet_rails_demo_app#2]
The question is, why use render instead of redirect?

**Comment by antulik** [comment]
Good point, it could be a redirect to fix that issue. 

Ideally I'd like to create some kind of pagelet communication system so changes in one pagelet could trigger refresh in other pagelets. The difference to a full page refresh is that you only reload changed data.

**Comment by antulik** [comment]
Updated to redirect
